import { useState, useEffect, useRef } from "react";
import { useLocation, useSearch } from "wouter";
import { 
  Terminal, 
  Play, 
  Settings, 
  Share2, 
  FileCode, 
  Folder, 
  ChevronRight, 
  ChevronDown, 
  Box, 
  Loader2,
  BrainCircuit,
  Server,
  Globe,
  Shield,
  Download,
  Database
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Badge } from "@/components/ui/badge";
import { useToast } from "@/hooks/use-toast";
import { useQuery } from "@tanstack/react-query";
import JSZip from "jszip";
import { saveAs } from "file-saver";

const mockFileSystem = [
  {
    name: "infrastructure",
    type: "folder",
    isOpen: true,
    children: [
      { name: "main.tf", type: "file", active: false },
      { name: "variables.tf", type: "file" },
      { name: "k8s-cluster.yaml", type: "file" },
    ]
  },
  {
    name: "src",
    type: "folder",
    isOpen: true,
    children: [
      { name: "api", type: "folder", isOpen: false, children: [] },
      { name: "workers", type: "folder", isOpen: false, children: [] },
      { name: "server.ts", type: "file", active: true },
    ]
  },
  { name: "docker-compose.prod.yml", type: "file" },
  { name: "Dockerfile", type: "file" },
];

export default function Builder() {
  const search = useSearch();
  const params = new URLSearchParams(search);
  const projectId = params.get("id");
  const { toast } = useToast();
  const terminalEndRef = useRef<HTMLDivElement>(null);

  // Fetch project data
  const { data: project } = useQuery({
    queryKey: ['project', projectId],
    queryFn: async () => {
      const res = await fetch(`/api/projects/${projectId}`);
      if (!res.ok) throw new Error('Failed to fetch project');
      return res.json();
    },
    enabled: !!projectId,
    refetchInterval: (data) => {
      // Poll every 1s if project is not complete
      return data?.status === 'complete' || data?.status === 'failed' ? false : 1000;
    },
  });

  // Fetch infrastructure template
  const { data: infrastructure } = useQuery({
    queryKey: ['infrastructure', projectId],
    queryFn: async () => {
      const res = await fetch(`/api/projects/${projectId}/infrastructure`);
      if (!res.ok) throw new Error('Failed to fetch infrastructure');
      return res.json();
    },
    enabled: !!projectId && project?.status === 'complete',
  });

  // Fetch build logs
  const { data: logs = [] } = useQuery({
    queryKey: ['logs', projectId],
    queryFn: async () => {
      const res = await fetch(`/api/projects/${projectId}/logs`);
      if (!res.ok) throw new Error('Failed to fetch logs');
      return res.json();
    },
    enabled: !!projectId,
    refetchInterval: 1000, // Poll logs every second
  });

  // Auto-scroll terminal
  useEffect(() => {
    terminalEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [logs]);

  // Show toast when complete
  useEffect(() => {
    if (project?.status === 'complete') {
      toast({
        title: "Architecture Complete",
        description: "Your platform infrastructure has been generated successfully.",
      });
    }
  }, [project?.status]);

  const handleDownloadArtifacts = async () => {
    if (!infrastructure) return;

    const zip = new JSZip();
    
    const infra = zip.folder("infrastructure");
    if (infrastructure.terraformConfig) {
      infra?.file("main.tf", infrastructure.terraformConfig);
    }
    if (infrastructure.kubernetesConfig) {
      infra?.file("k8s-cluster.yaml", infrastructure.kubernetesConfig);
    }
    if (infrastructure.dockerfileContent) {
      zip.file("Dockerfile", infrastructure.dockerfileContent);
    }
    
    zip.file("README.md", `# Platform Architecture for ${project?.name}\n\nGenerated by PlatformBuilder AI.\n\n## Deployment\nRun \`terraform apply\` to provision resources.`);

    const content = await zip.generateAsync({ type: "blob" });
    saveAs(content, "platform-architecture-bundle.zip");
    
    toast({
      title: "Artifacts Downloaded",
      description: "Terraform, Kubernetes, and Docker configurations saved.",
    });
  };

  const isBuilding = project?.status === 'analyzing' || project?.status === 'generating' || project?.status === 'pending';
  const isComplete = project?.status === 'complete';

  return (
    <div className="h-screen flex flex-col bg-background text-foreground overflow-hidden">
      {/* Builder Header */}
      <header className="h-14 border-b border-border bg-card/50 flex items-center justify-between px-4">
        <div className="flex items-center gap-4">
          <div className="font-mono font-bold text-lg tracking-tight flex items-center gap-2">
            <BrainCircuit className="h-5 w-5 text-primary" />
            Platform<span className="text-primary">Architect</span>
          </div>
          <div className="h-6 w-px bg-border" />
          <div className="flex items-center gap-2 text-sm">
             <Box className="h-4 w-4 text-muted-foreground" />
             <span className="font-medium">{project?.name || 'Loading...'}</span>
             <Badge variant="outline" className={`ml-2 ${isBuilding ? 'bg-primary/10 text-primary border-primary/20' : 'bg-green-500/10 text-green-500 border-green-500/20'}`}>
                {isBuilding ? "Architecting..." : isComplete ? "Ready" : project?.status}
             </Badge>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <Button variant="ghost" size="sm"><Share2 className="h-4 w-4 mr-2" /> Share</Button>
          
          {isComplete && infrastructure && (
            <Button 
              variant="outline" 
              size="sm" 
              className="animate-in fade-in slide-in-from-top-2 duration-500 border-primary/50 text-primary hover:bg-primary/10"
              onClick={handleDownloadArtifacts}
            >
              <Download className="h-4 w-4 mr-2" /> Download Artifacts
            </Button>
          )}

          <Button size="sm" className="bg-green-600 hover:bg-green-700 text-white font-bold" disabled={!isComplete}>
            <Play className="h-4 w-4 mr-2 fill-current" /> View Live
          </Button>
        </div>
      </header>

      {/* Main Workspace */}
      <div className="flex-1 flex overflow-hidden">
        {/* Sidebar */}
        <aside className="w-64 border-r border-border bg-card/20 flex flex-col">
          <div className="p-3 text-xs font-bold text-muted-foreground uppercase tracking-wider">Generated Infrastructure</div>
          <ScrollArea className="flex-1">
            <div className="px-2 space-y-1">
              {mockFileSystem.map((item, idx) => (
                <FileSystemItem key={idx} item={item} />
              ))}
            </div>
          </ScrollArea>
        </aside>

        {/* Editor Area */}
        <div className="flex-1 flex flex-col min-w-0 bg-background">
          {/* Editor Tabs */}
          <div className="flex h-10 border-b border-border bg-card/20">
            <div className="px-4 flex items-center gap-2 bg-background border-r border-border text-sm font-medium text-primary border-t-2 border-t-primary">
              <FileCode className="h-4 w-4" />
              server.ts
            </div>
            <div className="px-4 flex items-center gap-2 text-muted-foreground text-sm border-r border-border/50 hover:bg-card/40 cursor-pointer transition-colors">
              main.tf
            </div>
          </div>

          {/* Mock Editor Content */}
          <div className="flex-1 p-4 font-mono text-sm overflow-auto text-muted-foreground leading-relaxed">
            <div><span className="text-gray-500">// AI GENERATED: High-availability server entry point</span></div>
            <div><span className="text-purple-400">import</span> <span className="text-blue-400">{`{ Cluster }`}</span> <span className="text-purple-400">from</span> <span className="text-green-400">"ioredis"</span>;</div>
            <div><span className="text-purple-400">import</span> <span className="text-blue-400">{`{ Pool }`}</span> <span className="text-purple-400">from</span> <span className="text-green-400">"pg"</span>;</div>
            <br />
            <div><span className="text-gray-500">// Initialize connection pool with read replicas</span></div>
            <div><span className="text-purple-400">const</span> db = <span className="text-purple-400">new</span> Pool({`{`}</div>
            <div>&nbsp;&nbsp;host: <span className="text-green-400">process.env.DB_PRIMARY_HOST</span>,</div>
            <div>&nbsp;&nbsp;max: <span className="text-orange-400">20</span>,</div>
            <div>&nbsp;&nbsp;idleTimeoutMillis: <span className="text-orange-400">30000</span></div>
            <div>{`}`});</div>
          </div>

          {/* Terminal Panel */}
          <div className="h-64 border-t border-border bg-black/40 flex flex-col">
             <div className="flex items-center justify-between px-4 py-2 bg-card/20 border-b border-border/50">
                <div className="flex items-center gap-2 text-xs font-bold uppercase text-primary">
                  <BrainCircuit className="h-3 w-3" /> AI Architect Agent
                </div>
             </div>
             <ScrollArea className="flex-1 p-4 font-mono text-xs">
                <div className="space-y-1.5">
                  {logs.map((log: any, i: number) => (
                    <div key={i} className="flex gap-3 items-baseline">
                      <span className="text-muted-foreground select-none w-6 text-right opacity-30 text-[10px]">{i + 1}</span>
                      
                      {log.logLevel === "ai" && (
                        <span className="text-purple-400 font-bold flex items-center gap-2">
                          <BrainCircuit className="h-3 w-3" /> {log.message}
                        </span>
                      )}
                      {log.logLevel === "system" && <span className="text-blue-300 italic">{log.message}</span>}
                      {log.logLevel === "action" && (
                        <span className="text-orange-300 flex items-center gap-2">
                          <Server className="h-3 w-3" /> {log.message}
                        </span>
                      )}
                      {log.logLevel === "cmd" && <span className="text-muted-foreground">{log.message}</span>}
                      {log.logLevel === "info" && <span className="text-blue-300">{log.message}</span>}
                      {log.logLevel === "success" && <span className="text-green-400 font-bold">{log.message}</span>}
                      {log.logLevel === "error" && <span className="text-red-400 font-bold">{log.message}</span>}
                    </div>
                  ))}
                  {isBuilding && (
                    <div className="flex gap-2 items-center text-primary animate-pulse mt-2 pl-9">
                      <span className="h-2 w-2 bg-primary rounded-full animate-bounce" />
                      <span className="h-2 w-2 bg-primary rounded-full animate-bounce delay-75" />
                      <span className="h-2 w-2 bg-primary rounded-full animate-bounce delay-150" />
                    </div>
                  )}
                  <div ref={terminalEndRef} />
                </div>
             </ScrollArea>
          </div>
        </div>

        {/* Preview Panel */}
        <div className="w-80 border-l border-border bg-card/10 flex flex-col">
          <div className="p-3 border-b border-border text-xs font-bold text-muted-foreground uppercase tracking-wider">
            Infrastructure Map
          </div>
          <div className="flex-1 flex items-center justify-center bg-black/20 p-6">
             <div className="relative w-full h-full flex flex-col items-center justify-center gap-6">
                <div className={`flex flex-col items-center transition-all duration-500 ${logs.length > 2 ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-4'}`}>
                   <div className="h-12 w-12 rounded-full bg-blue-500/20 border border-blue-500/50 flex items-center justify-center">
                      <Globe className="h-6 w-6 text-blue-400" />
                   </div>
                   <span className="text-[10px] font-mono mt-2 text-blue-300">Global CDN</span>
                </div>

                <div className={`h-8 w-px bg-gradient-to-b from-blue-500/50 to-purple-500/50 transition-all duration-500 delay-200 ${logs.length > 3 ? 'opacity-100' : 'opacity-0'}`} />

                <div className={`flex flex-col items-center transition-all duration-500 delay-300 ${logs.length > 5 ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-4'}`}>
                   <div className="h-16 w-16 rounded-xl bg-purple-500/20 border border-purple-500/50 flex items-center justify-center relative">
                      <div className="absolute -top-2 -right-2 bg-green-500 text-black text-[9px] font-bold px-1.5 rounded-full">x20</div>
                      <Server className="h-8 w-8 text-purple-400" />
                   </div>
                   <span className="text-[10px] font-mono mt-2 text-purple-300">K8s Cluster</span>
                </div>

                <div className={`h-8 w-px bg-gradient-to-b from-purple-500/50 to-orange-500/50 transition-all duration-500 delay-500 ${logs.length > 6 ? 'opacity-100' : 'opacity-0'}`} />

                <div className={`flex gap-4 transition-all duration-500 delay-700 ${logs.length > 8 ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-4'}`}>
                   <div className="flex flex-col items-center">
                      <div className="h-10 w-10 rounded-lg bg-orange-500/20 border border-orange-500/50 flex items-center justify-center">
                         <Database className="h-5 w-5 text-orange-400" />
                      </div>
                      <span className="text-[10px] font-mono mt-2 text-orange-300">Postgres</span>
                   </div>
                   <div className="flex flex-col items-center">
                      <div className="h-10 w-10 rounded-lg bg-red-500/20 border border-red-500/50 flex items-center justify-center">
                         <Shield className="h-5 w-5 text-red-400" />
                      </div>
                      <span className="text-[10px] font-mono mt-2 text-red-300">Redis</span>
                   </div>
                </div>
             </div>
          </div>
        </div>
      </div>
    </div>
  );
}

function FileSystemItem({ item, level = 0 }: { item: any, level?: number }) {
  return (
    <div className="select-none">
      <div 
        className={`
          flex items-center gap-1.5 py-1 px-2 rounded-sm cursor-pointer text-sm
          ${item.active ? 'bg-primary/20 text-primary font-medium' : 'text-muted-foreground hover:text-foreground hover:bg-muted/50'}
        `}
        style={{ paddingLeft: `${level * 12 + 8}px` }}
      >
        {item.type === 'folder' ? (
           <>
             {item.isOpen ? <ChevronDown className="h-3 w-3" /> : <ChevronRight className="h-3 w-3" />}
             <Folder className={`h-3.5 w-3.5 ${item.isOpen ? 'fill-blue-400/20 text-blue-400' : ''}`} />
           </>
        ) : (
           <FileCode className="h-3.5 w-3.5" />
        )}
        <span className="truncate">{item.name}</span>
      </div>
      {item.type === 'folder' && item.isOpen && item.children && (
        <div>
          {item.children.map((child: any, idx: number) => (
            <FileSystemItem key={idx} item={child} level={level + 1} />
          ))}
        </div>
      )}
    </div>
  )
}